- uses: game-ci/unity-test-runner@v2
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    projectPath: path/to/your/project
    githubToken: ${{ secrets.GITHUB_TOKEN }}

- uses: game-ci/unity-test-runner@v2
  with:
    githubToken: ${{ secrets.GITHUB_TOKEN }}

- uses: actions/upload-artifact@v2
  if: always()
  with:
    name: Test results
    path: artifacts